"""empty message

Revision ID: 09291d88114b
Revises: 26210c8ab883
Create Date: 2023-08-30 13:06:43.662806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09291d88114b'
down_revision = '26210c8ab883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_column('posted_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_on', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
