"""empty message

Revision ID: 26210c8ab883
Revises: 351040b14b63
Create Date: 2023-08-30 11:09:43.567192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26210c8ab883'
down_revision = '351040b14b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_status')
    # ### end Alembic commands ###
