"""empty message

Revision ID: 351040b14b63
Revises: 458c50f22ae4
Create Date: 2023-08-29 21:36:46.376447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351040b14b63'
down_revision = '458c50f22ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('posted_on')

    # ### end Alembic commands ###
