"""empty message

Revision ID: 39b65280ba59
Revises: d04483d9a769
Create Date: 2023-09-24 17:47:49.200211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b65280ba59'
down_revision = 'd04483d9a769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_upload', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('image_upload')
        batch_op.drop_column('job_image')

    # ### end Alembic commands ###
