"""empty message

Revision ID: b506737ddbd0
Revises: 39b65280ba59
Create Date: 2023-09-25 13:06:24.571061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b506737ddbd0'
down_revision = '39b65280ba59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bid_SS', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('SS_upload', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bid_difference', sa.DateTime(), nullable=True))
        batch_op.drop_column('image_upload')
        batch_op.drop_column('job_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_image', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('image_upload', sa.DATETIME(), nullable=True))
        batch_op.drop_column('bid_difference')
        batch_op.drop_column('SS_upload')
        batch_op.drop_column('bid_SS')

    # ### end Alembic commands ###
