"""empty message

Revision ID: e05b9d60a880
Revises: 65f05afe55f1
Create Date: 2023-09-25 15:53:49.961222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05b9d60a880'
down_revision = '65f05afe55f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SS_upload_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bid_time_difference', sa.String(), nullable=True))
        batch_op.drop_column('SS_upload')
        batch_op.drop_column('bid_difference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bid_difference', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('SS_upload', sa.DATETIME(), nullable=True))
        batch_op.drop_column('bid_time_difference')
        batch_op.drop_column('SS_upload_time')

    # ### end Alembic commands ###
